### ISSUE TITLE
使用「最近八小时」来判断批次并不准确

### ISSUE THREAD

**Issue by oldherl** [a-wing/KISS2UI#1]
比如说1点开始的一批，我2点去看页面，那么前八小时是18点之后，也就是包括了很多上一批次的。

如果由于技术原因不方便记录批次的开始时间，不如删掉这个橙红色的、颜色和failed很像的new标签。

**Comment by a-wing** [comment]
https://github.com/a-wing/KISS2U/issues/2

是不准确。感觉比没有好点（

**Comment by a-wing** [comment]
在 kiss2ugo 的 API 上增加了 https://github.com/a-wing/kiss2ugo/commit/0681468971a40232b7bc7354332cdb0a0fe337d8

文档在这个： https://build.archlinuxcn.org/api/v2/docs/#/?id=gethotpackages

在 kiss2ui 的界面上加了判断新包的条件 https://github.com/a-wing/KISS2UI/commit/0dacea22b9020df110d6d380d3ef0accc93cb9dd
